matrix:
  include:
    - language: java
      jdk: oraclejdk8

    - language: node_js
      node_js: 8.11.1


language: java

services:
  - docker
script:
  - docker build -t danshan/shanhh-hexo .

notifications:
  slack: shanhonghao:pdqZbe3SSqGZahgfKsddxPE5
